Support networkMode=awsvpc
signal-ai/prometheus-ecs-sd pull request #3
Opened 2018-10-11 03:27 UTC by alrosot

When that happens, there will never be a network binding, but the task should still be considered

2018-10-11 04:37 UTC, alrosot commented
Please hold on this PR. I just realised that some target IP addresses are getting mixed. Maybe it was my fault.

2019-02-25 18:14 UTC, fredsig requested changes
Thanks for the PR and apologies for the delay. Although we're caching the self.task_definition_cache.get call, I would prefer to not do it outside the no_network_binding loop as there is no need to get the task definition for every running task. Something like this would be enough on line 136:

if ('networkBindings' not in container or len(container['networkBindings']) == 0) and len(container['networkInterfaces']) == 0:

This way, tasks using awsvpc will not be added to the no_network_binding list as we should have a private ip address under 'networkInterfaces'.

2019-02-25 18:17 UTC, fredsig reviewed
Having a look at this. Seems ok for now as it should just expect a single private ip. We might have an issue if you set awsvpc, enabled Prometheus but forgot to set a port, so we should have a default port set for this.

2019-04-26 09:32 UTC, fredsig commented
@alrosot Did you had the chance to look at my previews comments? Thanks.

2019-07-05 12:24 UTC, alrosot commented
Sorry @fredsig, I got disconnected from github for a while. I'll review your comments.

2019-07-05 13:07 UTC, alrosot commented
I stopped doing devops since last year, so it was a bit hard to remember the context of this chance. But believe it or not, I guess I hit exactly the same problem you described with ports one day after I raised this PR.
So I just added my commit from 2018-10-12 into this PR. I hope it makes sense.
Thanks!

2019-07-25 16:22 UTC, fredsig commented
I ran into several issues on my test environment.

1. Defaulting to port 9100 if you don't set it on PROMETHEUS_PORT breaks dynamic port discovery for containers running the bridge network mode.
2. The lambda to get the private ip:

eni = list(filter(lambda x: x.get('PrivateIpAddress') != task_info.ec2_instance['PrivateIpAddress'], task_info.ec2_instance.get('NetworkInterfaces')))[0]

doesn't work well if you have multiple attached private ips to a given ec2 instance, so it's better to instead use it like:

interface_ip = container['networkInterfaces'][0]['privateIpv4Address']

3. It breaks containers with PROMETHEUS_NOLABELS set.

I really appreciate your work and submitting this PR, but since I want to get this working with awsvpc networking, I'm going to close this PR and commit my changes today. Thanks again!

2019-07-25 16:22 UTC, closed without merging